# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    curl --location https://github.com/accurics/terrascan/releases/download/v1.18.3/terrascan_1.18.3_Linux_x86_64.tar.gz --output terrascan.tar.gz
    tar -xvf terrascan.tar.gz
    sudo install terrascan /usr/local/bin    
  displayName: 'Get tools'

- script: |
    terrascan scan -t azure -i terraform --output junit-xml > $(Build.DefaultWorkingDirectory)/terrascan-results.xml
  workingDirectory: $(System.DefaultWorkingDirectory)/infrastructure/storage-account
  displayName: 'Run terrascan'  

- task: PublishTestResults@2
  displayName: "Terrascan Results"
  condition: succeededOrFailed()
  inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "**/terrascan-*.xml"
      searchFolder: "$(Build.DefaultWorkingDirectory)"
      mergeTestResults: false
      testRuntitle: Terrascan
      failTaskOnFailedTests: true
      publishRunAttachments: true